# components/train_component.yml

name: train_model
display_name: Train Model Component
version: 1
type: command

inputs:
  training_data:
    type: uri_folder
    description: "Folder containing selected_features.csv"

  model_type:
    type: string
    enum: ["logistic", "randomforest", "xgboost"]
    description: "Choose model to train"

outputs:
  model_output:
    type: uri_folder
    description: "Folder where model.joblib will be saved"

command: >
  python src/train.py
  --training_data ${{inputs.training_data}}
  --model_output ${{outputs.model_output}}
  --model_type ${{inputs.model_type}}

environment:
  image: mcr.microsoft.com/azureml/sklearn-1.0-ubuntu20.04-py38-cpu

description: |
  Trains a machine learning model using Logistic Regression, 
  RandomForest, or XGBoost and outputs model.joblib.