# components/train_component.yml

name: train_model
display_name: Train Model Component
version: 1
type: command

inputs:
  training_data:
    type: uri_folder
    description: "Folder containing selected_features.csv"

  model_type:
    type: string
    optional: false
    enum: ["logistic", "randomforest", "xgboost"]
    description: "Choose which model to train."

outputs:
  model_output:
    type: uri_folder
    description: "Folder where model.joblib will be saved"

command: >
  python src/train.py
  --training_data ${{inputs.training_data}}
  --model_output ${{outputs.model_output}}
  --model_type ${{inputs.model_type}}

environment:
  conda_file: ../environments/sklearn-env.yml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04

description: |
  Trains a machine learning model for anomaly detection using
  logistic regression, random forest, or XGBoost based on input parameters.
  Outputs a model artifact (model.joblib) that can be registered and deployed.