# components/train_component.yml

name: train_model_v2
display_name: Train Model Component
version: 1
type: command

inputs:
  training_data:
    type: mltable

  model_type:
    type: string


outputs:
  model_output:
    type: uri_folder
    description: "Folder where model.joblib will be saved"

command: >
  python src/train.py
  --training_data ${{inputs.training_data}}
  --model_output ${{outputs.model_output}}
  --model_type ${{inputs.model_type}}

environment: 
  image: mcr.microsoft.com/azureml/sklearn-1.0-ubuntu20.04-py38-cpu