$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model
display_name: Train Model Component
type: command
version: 1
description: Trains a machine learning model using selected features.

inputs:
  training_data:
    type: mltable   # CHANGED from uri_file → mltable
  model_type:
    type: string

outputs:
  model_output:
    type: uri_folder

code: ../src
environment: azureml:AzureML-sklearn-1.3:1

command: >-
  python train.py
  --training_data ${{inputs.training_data}}
  --model_type ${{inputs.model_type}}
  --model_output ${{outputs.model_output}}
