$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

compute: cpu-cluster

inputs:
  raw_data:
    type: mltable
  model_type:
    type: string

outputs:
  trained_model:
    type: uri_folder

jobs:

  preprocess_step:
    type: command
    component: azureml:prep_data:1
    inputs:
      input_data: ${{ parent.inputs.raw_data }}
    outputs:
      output_data: ${{ parent.jobs.preprocess_step.outputs.output_data }}

  feature_selection_step:
    type: command
    component: azureml:feature_selection:1
    inputs:
      processed_data: ${{ parent.jobs.preprocess_step.outputs.output_data }}
    outputs:
      selected_data: ${{ parent.jobs.feature_selection_step.outputs.selected_data }}

  train_step:
    type: command
    component: azureml:train_model:1
    inputs:
      training_data: ${{ parent.jobs.feature_selection_step.outputs.selected_data }}
      model_type: ${{ parent.inputs.model_type }}
    outputs:
      model_output: ${{ parent.outputs.trained_model }}
