$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: anomaly-detection-pipeline
compute: cpu-cluster1

inputs:
  raw_data:
    type: mltable
    path: azureml:clean_lo2_full:2

outputs:
  trained_model:
    type: uri_folder

jobs:

  preprocess_step:
    type: command
    component: azureml:prep_data_v2:3
    inputs:
      input_data: ${{parent.inputs.raw_data}}
    outputs:
      output_data:
        type: mltable

  feature_selection_step:
    type: command
    component: azureml:feature_selection_v2:3
    inputs:
      input_data: ${{parent.jobs.preprocess_step.outputs.output_data}}
    outputs:
      output_data:
        type: mltable

  train_step:
    type: command
    component: azureml:train_model_v2:3
    inputs:
      training_data: ${{parent.jobs.feature_selection_step.outputs.output_data}}
      model_type: xgboost
    outputs:
      model_output: ${{parent.outputs.trained_model}}
