$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: anomaly-detection-pipeline
compute: cpu-cluster1

inputs:
  raw_data:
    type: mltable
  model_type:
    type: string
    default: xgboost

outputs:
  trained_model:
    type: uri_folder

jobs:

  preprocess_step:
    type: command
    component: azureml:prep_data@latest
    inputs:
      input_data: ${{parent.inputs.raw_data}}
    outputs:
      output_data: ${{parent.jobs.preprocess_step.outputs.output_data}}

  feature_selection_step:
    type: command
    component: azureml:feature_selection@latest
    inputs:
      processed_data: ${{parent.jobs.preprocess_step.outputs.output_data}}
    outputs:
      selected_data: ${{parent.jobs.feature_selection_step.outputs.selected_data}}

  train_step:
    type: command
    component: azureml:train_model@latest
    inputs:
      training_data: ${{parent.jobs.feature_selection_step.outputs.selected_data}}
      model_type: ${{parent.inputs.model_type}}
    outputs:
      model_output: ${{parent.outputs.trained_model}}